version: "3.8"

services:
  db:
    image: mariadb:10.5
    container_name: nagiosql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - monitor_net

  nagios:
    image: badshashorif/nagios-core-nagiosql:latest
    container_name: nagios
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: nagiosql
      DB_USER: nagiosqluser
      DB_PASS: nagiosqlpass
      ADMIN_DB_USER: root
      ADMIN_DB_PASS: rootpass
      NAGIOS_ADMIN_USER: nagiosadmin
      NAGIOS_ADMIN_PASS: NagiosAdmin
      NAGIOSQL_ADMIN_USER: admin
      NAGIOSQL_ADMIN_PASS: admin123
    depends_on:
      - db
    volumes:
      - nagios_data:/usr/local/nagios/etc
      - nagios_var:/usr/local/nagios/var
      - nagios_qldata:/var/www/html/nagiosql
    networks:
      - monitor_net

volumes:
  db_data:
  nagios_data:
  nagios_var:
  nagios_qldata:

networks:
  monitor_net:
    driver: bridge
